import { Opportunity } from "./types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "Food Bank Assistant",
    organization: "Community Food Bank",
    description: "Help sort and distribute food to families in need. No experience required, just a willing heart to serve.",
    category: "Food Security",
    location: "Downtown Community Center",
    date: "Every Saturday",
    spots: 5,
  },
  {
    id: "2",
    title: "Youth Mentor",
    organization: "Big Brothers Big Sisters",
    description: "Make a difference in a child's life by becoming a mentor. Weekly commitment required.",
    category: "Education",
    location: "Various Locations",
    date: "Flexible Schedule",
    spots: 10,
  },
  {
    id: "3",
    title: "Park Cleanup Volunteer",
    organization: "Green Earth Initiative",
    description: "Join our monthly park cleanup effort to keep our community beautiful and environmentally friendly.",
    category: "Environment",
    location: "Central Park",
    date: "First Sunday of each month",
    spots: 15,
  },
  {
    id: "4",
    title: "Senior Companion",
    organization: "Elder Care Alliance",
    description: "Provide companionship and assistance to seniors in our community. Training provided.",
    category: "Healthcare",
    location: "Senior Living Centers",
    date: "Weekday afternoons",
    spots: 8,
  },
  {
    id: "5",
    title: "Animal Shelter Helper",
    organization: "Happy Paws Rescue",
    description: "Help care for rescued animals and assist with shelter operations. Perfect for animal lovers!",
    category: "Animal Welfare",
    location: "Happy Paws Shelter",
    date: "Weekends",
    spots: 6,
  },
  {
    id: "6",
    title: "Literacy Tutor",
    organization: "Reading Partners",
    description: "Help adults and children improve their reading skills. Training and materials provided.",
    category: "Education",
    location: "Public Library",
    date: "Tuesday & Thursday evenings",
    spots: 4,
  },
];